#!/bin/bash

function clean {    # Clean things
    rm leibnizc leibnizlcs bin/Release/net8.0/linux-x64/publish/dotnetaot  bin/Debug/net8.0/dotnetaot.dll
}

function build {    # Build stuff
  clean
  pushd .. > /dev/null
  ./Taskfile build
  popd > /dev/null
  echo -n BUILD DOTNET
  time dotnet build  --nologo -v q
  echo BUILD DOTNETAOT
  time dotnet publish
  echo -n BUILD GCC
  time gcc -Ofast -x c Program.cs -oleibnizc
  echo -n BUILD LCS
  time ../lcs -O -oleibnizlcs ./Program.cs
  cp /home/lucabol/dev/lsharp/dotnetaot/bin/Release/net8.0/linux-x64/publish/dotnetaot ./leibnizcdotnet
  echo SIZES
  exa -lrs size leib*
}

function perf {    # Perf test
  hyperfine -i ./leibnizc ./leibnizcdotnet ./leibnizlcs 
}

function help {     # Prints help
    echo "Usage: $0 <task> <args>"
    echo "Execute a task with the specified arguments."
    echo "By adding 'alias run=./Taskfile' you can then call it as 'run <task> <args>"
    echo
    echo "Tasks:"
    grep '^function .* #.* ' Taskfile | # Start with function and has # somewhere
      cut -d' ' -f 2- |                 # Remove the word 'function'
      tr -d '{' |                       # Remove '{}'
      sed 's/^/  /g' |                  # Indent by two spaces
      column --table --separator '#'    # column it using # as the separator
}

${@:-help}
