#!/bin/bash
DBGDIR=debug

usage()
{
	echo "usage: lcsc [GCCFLAGS] file.cs" >&2
	exit 1
}

for i
do
	case $i in
	-*)
		flags="$flags $i"
    if [[ "$i" == "-g" ]]; then
      debug=true
    fi
		;;
	*)
		if ! test -z $file
		then
			usage
		fi
		file=$i
		;;
	esac
done

if test -z $file
then
	usage
fi

PRE="${file%.*}"
DBGNAME=`basename $PRE`

debugbuild() {

  ./lcs $file > "$DBGDIR/$DBGNAME.c"
  gcc $flags $DBGDIR/$DBGNAME.c
}
releasebuild() {
  
  ./lcs $file | gcc $flags -xc -
}

if [ "$debug" ]; then
  debugbuild
else
  releasebuild
fi
