#!/bin/bash
DBGDIR=debug

usage()
{
	echo "usage: lcsc [GCCFLAGS] file.cs" >&2
	exit 1
}

for i
do
	case $i in
	-*)
		flags="$flags $i"
		;;
	*)
		if ! test -z $file
		then
			usage
		fi
		file=$i
		;;
	esac
done

if test -z $file
then
	usage
fi

PRE="${file%.*}"
BNAMES=`basename -a $PRE`


./lcs $file

if [ $? -eq 0 ]; then
  gcc -Wall -Wextra -fno-diagnostics-show-caret -fno-show-column $flags /tmp/$BNAMES.c -lm
fi
