#!/bin/bash

TARGET="lcs.bak"

function clean {    # Clean things
    rm *.o lcs
}

function commonbuild {

  pushd .. > /dev/null
  ./Taskfile build
  popd > /dev/null

  ../src/lcs  -o $TARGET $1 *.cs
}
function build {    # Build debug
  commonbuild "-g"
}
function buildr {    # Build speed
  commonbuild "-O"
}

function buildt {    # Build speed
  commonbuild "-g -D TEST"
}

function run {    # Runs something
  buildt
  ./$TARGET
}

function help {     # Prints help
    echo "Usage: $0 <task> <args>"
    echo "Execute a task with the specified arguments."
    echo "By adding 'alias run=./Taskfile' you can then call it as 'run <task> <args>"
    echo
    echo "Tasks:"
    grep '^function .* #.* ' Taskfile | # Start with function and has # somewhere
      cut -d' ' -f 2- |                 # Remove the word 'function'
      tr -d '{' |                       # Remove '{}'
      sed 's/^/  /g' |                  # Indent by two spaces
      column --table --separator '#'    # column it using # as the separator
}

${@:-help}
